name: chat
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  analyzer: ^2.0.0
  auto_route: ^2.2.0
  cloud_firestore: ^2.4.0
  cupertino_icons: ^1.0.3
  dartz: 0.10.0-nullsafety.2
  firebase_analytics: ^8.2.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_crashlytics: ^2.1.1
  flutter_bloc: ^7.0.1
  flutter_hooks: ^0.17.0
  flutter_slidable: ^0.6.0
  freezed_annotation: ^0.14.3
  get_it: null
  google_sign_in: ^5.0.4
  hooks_riverpod: ^0.14.0+4
  implicitly_animated_reorderable_list: ^0.4.0
  injectable: ^1.4.1
  json_annotation: ^4.1.0
  kt_dart: ^0.9.1
  meta: ^1.7.0
  provider: ^5.0.0
  rxdart: ^0.27.1
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^2.1.0
  build_runner: null
  flutter_lints: ^1.0.4
  freezed: ^0.14.3
  injectable_generator: ^1.4.1
  json_serializable: ^5.0.0

dependency_overrides:
  analyzer: ^1.5.0
  meta: ^1.3.0

flutter:
  uses-material-design: true
